Removed: p10k, hyperjs, vscode configs Added: starship, alacritty, new zshrc

diff --git a/dot_zshrc b/dot_zshrc
--- a/dot_zshrc
+++ b/dot_zshrc
@@ -1,18 +1,4 @@
-# Pyenv setup
-export PYENV_ROOT="$HOME/.pyenv"
-export PATH="$PYENV_ROOT/bin:$PATH"
-eval "$(pyenv init -)"
-eval "$(pyenv virtualenv-init -)"
-
-# Go setup
-export PATH=$PATH:/usr/local/go/bin
-
-# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
-# Initialization code that may require console input (password prompts, [y/n]
-# confirmations, etc.) must go above this block; everything else may go below.
-if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
-  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
-fi
+################################## oh-my-zsh ##################################
 
 # If you come from bash you might have to change your $PATH.
 # export PATH=$HOME/bin:/usr/local/bin:$PATH
@@ -24,7 +10,7 @@ export ZSH="$HOME/.oh-my-zsh"
 # load a random theme each time oh-my-zsh is loaded, in which case,
 # to know which specific one was loaded, run: echo $RANDOM_THEME
 # See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
-ZSH_THEME="powerlevel10k/powerlevel10k"
+# ZSH_THEME=""
 
 # Set list of themes to pick from when loading at random
 # Setting this variable when ZSH_THEME=random will cause zsh to load
@@ -87,6 +73,7 @@ ZSH_THEME="powerlevel10k/powerlevel10k"
 # Example format: plugins=(rails git textmate ruby lighthouse)
 # Add wisely, as too many plugins slow down shell startup.
 plugins=(
+  archlinux
   aws
   git
   docker
@@ -134,8 +121,16 @@ source $ZSH/oh-my-zsh.sh
 # Example aliases
 # alias zshconfig="mate ~/.zshrc"
 # alias ohmyzsh="mate ~/.oh-my-zsh"
-alias ll="ls -l"
-export PATH="$PATH:$HOME/.local/bin"
+
+#################################### shell ####################################
+# Starship
+eval "$(starship init zsh)"
+
+# nvm
+source /usr/share/nvm/init-nvm.sh
+
+# I'm so clumsy
+alias celar="echo door"
 
 # k8s config
 alias k="kubectl"
@@ -145,25 +140,57 @@ export KUBE_EDITOR='code --wait'
 # xclip
 alias c="xclip -selection clipboard"
 
-# Gitlab
-export GITLAB_TOKEN=""
-export GITLAB_USERNAME=""
+# zoxide
+eval "$(zoxide init zsh)"
+alias cd="z"
 
-# pip
-export PIP_EXTRA_INDEX_URL="https://__token__:$GITLAB_TOKEN@git.sia-partners.com/api/v4/groups/444/-/packages/pypi/simple https://__token__:$GITLAB_TOKEN@git.sia-partners.com/api/v4/projects/867/packages/pypi/simple"
+################################### python ####################################
 
-# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
-[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
+# Pyenv setup
+export PYENV_ROOT="$HOME/.pyenv"
+export PATH="$PYENV_ROOT/bin:$PATH"
+eval "$(pyenv init -)"
 
-export NVM_DIR="$HOME/.nvm"
-[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
-[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
+# helper functions
+function clean-path-name(){
+    echo ${1//\//-}
+}
 
-# Brew
-eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
+function get-venv-name(){
+    # venv name
+    if [[ -z $1 ]]; then
+        venv_name=$(basename $(pwd))
+    else
+        venv_name=$1
+    fi
+    venv_name=$(clean-path-name $venv_name)
+    echo $venv_name
+}
 
-# I'm so clumsy
-alias celar="echo door"
+# pyenv wrapper
+function venv-create(){
+    # python version
+    if [[ -z $1 ]]; then
+        echo "Missing python version"
+        return 1
+    fi
+
+    venv_name=$(get-venv-name $2)
+
+    pyenv virtualenv $1 $venv_name && pyenv activate $venv_name
+}
+
+alias venv-list="pyenv virtualenvs"
+
+function venv-activate(){
+    venv_name=$(get-venv-name $1)
+    pyenv activate $venv_name
+}
+
+function venv-delete(){
+    venv_name=$(get-venv-name $1)
+    pyenv virtualenv-delete $venv_name
+}
 
 # Poetry util
 function fix-poetry-lock(){
@@ -172,37 +199,54 @@ function fix-poetry-lock(){
         return 1
     fi
 
-    POETRY_PROJECTS=()
-    FIND_POETRY_PROJECTS=$(find $1 -name "*pyproject.toml" -not -path "./.git/*" -exec dirname {} \;)
+    poetry_projects=()
+    find_poetry_projects=$(find $1 -name "*pyproject.toml" -not -path "./.git/*" -exec dirname {} \;)
 
     # Read each line into the array
     while IFS= read -r file; do
-        POETRY_PROJECTS+=("$file")
-    done <<< "$FIND_POETRY_PROJECTS"
+        poetry_projects+=("$file")
+    done <<< "$find_poetry_projects"
 
     # User input for safeguard
-    echo "Found ${#POETRY_PROJECTS[@]} poetry projects in $(readlink -f $1)"
+    echo "Found ${#poetry_projects[@]} poetry projects in $(readlink -f $1)"
     echo "Proceed ? [y/n]"
     read -r ANS
 
-    CLEAN_ANS=$(echo "$ANS" | tr '[:upper:]' '[:lower:]')
-    if [[ ${CLEAN_ANS:0:1} == "y" ]]; then
+    clean_ans=$(echo "$ANS" | tr '[:upper:]' '[:lower:]')
+    if [[ ${clean_ans:0:1} == "y" ]]; then
         # Check and fix poetry projects
-        for POETRY_PROJECT in ${POETRY_PROJECTS[@]}; do
-            POETRY_PROJECT_FULL=$(readlink -f $POETRY_PROJECT)
+        for poetry_project in ${poetry_projects[@]}; do
+            poetry_project_full=$(readlink -f $poetry_project)
 
-            echo "> checking ${POETRY_PROJECT}"
-            poetry check --directory=$POETRY_PROJECT_FULL || poetry lock --no-update --directory=$POETRY_PROJECT_FULL
+            echo "> checking ${poetry_project}"
+            poetry check --directory=$poetry_project_full || poetry lock --no-update --directory=$poetry_project_full
         done
     else
         return 0
     fi
 }
 
+# Created by `pipx` on 2024-04-29 12:13:33
+export PATH="$PATH:/home/clement/.local/bin"
+eval "$(register-python-argcomplete pipx)"
+
+################################### docker ####################################
+docker() {
+  case $1 in
+    ps)
+      shift
+      command dops "$@"
+      ;;
+    *)
+      command docker "$@";;
+  esac
+}
+
+#################################### misc #####################################
 function init-scraping(){
     if [[ -z $1 ]]; then
         echo "No source passed"
-        return 1
+        exit 1
     fi
 
     # docker compose down
@@ -212,4 +256,9 @@ function init-scraping(){
     export PROJECT_CONFIG=$(cat conf/project_config.yml)
     export PROVIDER_CREDENTIALS=$(cat conf/provider_credentials.json)
     export SOURCE=$1
+    export DEBUG=True
+}
+
+function copy-task-tag() {
+    git branch --show-current | sed 's/\//\-/g' | c
 }
